# Generated by Django 2.0 on 2018-10-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcuser',
            name='additional_data',
            field=models.TextField(null=True),
        ),
    ]
