# Generated by Django 2.0 on 2018-10-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0002_tcuser_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date_published',
            field=models.DateTimeField(auto_now=True, verbose_name='Like date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(auto_now=True, verbose_name='Post date'),
        ),
    ]
