# Generated by Django 2.0 on 2018-10-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0003_auto_20181003_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
